### ISSUE TITLE
Eject Seat

### ISSUE THREAD

**Issue by vsv7nau** [JLealos/cs386-a2.1#4]
Upon pressing eject button the seat deploys out of the cabin

**Comment by JLealos** [comment]
Yeah my girlfriend talks to much, sometimes you need to kick her out.

**Comment by rudraamin06** [comment]
I wish I had this in my car as well, would love to kick people out and say it was just a prank bro.

**Comment by clw549** [comment]
@vsv7nau we need you to get on this like yesterday.

**Comment by rudraamin06** [comment]
@vsv7nau come on broooo, can you just fix the issue mane. It's not that hard

**Comment by vsv7nau** [comment]
No.

**Comment by rudraamin06** [comment]
#5 @vsv7nau  caused this issue. #interns am I right?
